name: Daily WhatsApp Quote
on:
  schedule:
    - cron: '0 1 * * *'  # Runs at 7 AM IST (1 AM UTC)
  workflow_dispatch:       # Allows manual runs
jobs:
  send-quote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install twilio requests
      - name: Run WhatsApp Bot
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          YOUR_WHATSAPP_NUM: ${{ secrets.YOUR_WHATSAPP_NUM }}
        run: |
          python -c "
          from twilio.rest import Client;
          import requests;
          import os;
          quote = requests.get('https://zenquotes.io/api/random').json()[0];
          client = Client(os.environ['TWILIO_ACCOUNT_SID'], os.environ['TWILIO_AUTH_TOKEN']);
          message = client.messages.create(
              body=f'🔥 Daily Quote:\\n\\n{quote[\"q\"]}\\n—{quote[\"a\"]}',
              from_='whatsapp:+14155238886',
              to=f'whatsapp:{os.environ[\"YOUR_WHATSAPP_NUM\"]}'
          );
          print('✅ Quote sent!');
          "
